### ISSUE TITLE
Prisma upsert errors occasionally

### ISSUE THREAD

**Issue by pavo-etc** [pavo-etc/penultimate-guitar#46]
Need to check if this is due to UG rate limiting or something else

**Comment by pavo-etc** [comment]
```
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: \nInvalid `prisma.tab.upsert()` invocation:\n\n\nUnique constraint failed on the fields: (`taburl`)","reason":{"errorType":"Error","errorMessage":"\nInvalid `prisma.tab.upsert()` invocation:\n\n\nUnique constraint failed on the fields: (`taburl`)","code":"P2002","clientVersion":"4.12.0","meta":{"target":["taburl"]},"stack":["Error: ","Invalid `prisma.tab.upsert()` invocation:","","","Unique constraint failed on the fields: (`taburl`)","    at fn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:174:6477)","    at fn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:174:5907)","    at fn.request (/var/task/node_modules/@prisma/client/runtime/library.js:174:5786)","    at async t._request (/var/task/node_modules/@prisma/client/runtime/library.js:177:10477)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ","Invalid `prisma.tab.upsert()` invocation:","","","Unique constraint failed on the fields: (`taburl`)","    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)","    at process.emit (node:events:525:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
```

**Comment by pavo-etc** [comment]
Insertion errors should not result in 500 errors anymore, all are caught (and it doesn't really matter from a user perspective if the insertion fails, it will just pull it again)

**Comment by pavo-etc** [comment]
This doesn't solve the underlying issues though

**Comment by pavo-etc** [comment]
A few different kinds of errors:
- Unique constraint failed on the fields: (`taburl`)
- Too many clients
